### ISSUE TITLE
Exception when calling CJSBridge::GetCmdList function

### ISSUE THREAD

**Issue by Kris-88** [roytam1/kmeleon#12]
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	k-meleon.exe
  Application Version:	76.3.1.0
  Application Timestamp:	5fa5768d
  Fault Module Name:	macros.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	5f77b3bc
  Exception Code:	c0000005
  Exception Offset:	0001146b

Problem occured in k-meleon\kplugins\macros2\macros.cpp,
function GetCmds, line 796:
if (iter->second.ismacro() && iter->second.md->macroInfo)
and the same in line 803.

second.md is null if an undefined macro call is present somewhere in the .kmm files.
And now we have the one - _Translate_BabelFish_SetDefaults in translate.kmm.

I suggest checking the md field instead of md-> macroInfo, because this is not a problem when there is no macroInfo in the macro. We have many of these macros, and EvalExpr handles this situation correctly. But this is a problem when the macro is not defined. We must skip it on the list.

**Comment by roytam1** [comment]
your suggested changes are in, lets see what happen in next build.

**Comment by Kris-88** [comment]
Now everything is OK.
Thank you.
