### ISSUE TITLE
Unhandled exception at module xul.dll: Access violation reading location...

### ISSUE THREAD

**Issue by MrkRe900** [roytam1/kmeleon#13]
I downloaded KM from latest build fork with Goanna engine. This current version plays youtube videos perfect with HD resolution compared to previous versions. But sometimes the browser crashes with some random websites and it will crash every time I try to watch any video at https://www.censored.tv/
When browser crashes my system debugger reports error in a module xul.dll - Unhandled exception at module xul.dll: Access violation reading location...

If you can point me a symbols file for this build of xul.dll module I can debug for failing source code line.

Used version: KM76.4.4-Goanna-20210724
System environment: Windows XP Professional x64 Edition Version 2003 SP 2

K-MELEON VERSION :
readme.html EN:    ( -- )
version.ini:  exe=33751108=2.3.0044   => in KM 76.1.1 Goanna? +newer +?
platform-prefs:   (--)       (Gecko engine?)
platform.ini:  MS 3.5.0   => in KM KM-Goanna
platform.ini:  BuildID=20210723024210 / v3.5.0
general.useragent.vendor + vendorSub  =  ( -- )  
Macros:  injectJS returns OK

**Comment by roytam1** [comment]
you may try disabling dom.workers.enabled in about:config

**Comment by MrkRe900** [comment]
Disabling dom.workers.enabled solved my problem!
Thank you roytam1 !
