### ISSUE TITLE
post new releases here

### ISSUE THREAD

**Issue by leao-nardo** [roytam1/kmeleon#18]
i see in the site theres many newer buils , last one from last week . but theres no builds beein posted here . 
in your site the dowload buton lead to a forum post. it all seem quite messy .
u could be posting here too. would be more organized .

**Comment by roytam1** [comment]
blog post comes with a direct download, and also directory in download server is browsable.
uploading to here is last resort when download server is not working so I normally don't do this.

**Comment by leao-nardo** [comment]
to be clear , a person that arrives here on this git may think that its AdanbonWare for how it seems . 
so for one arriving here i will leave the links u say right
http://kmeleonbrowser.org/forum/read.php?19,154431
this is the forum post . where releases are being posted .
http://kmeleonbrowser.org/forum/read.php?19,154431,page=31
thats the last page by today

and last post:
Re: [TEST BUILD] K-Meleon 76.5.0 on Goann 3.6.0 (Build 20240106)
Posted by: [roytam1](http://kmeleonbrowser.org/forum/profile.php?19,4676)
Date: January 05, 2024 11:35PM

New regular/weekly KM-Goanna release:
https://o.rthost.win/kmeleon/KM76.5.0-Goanna-20240106.7z

and this last link is the current , by today, last test build . for anyone looking for. its portable , just download and unzip.

**Comment by ioc2e3** [comment]
Here ( http://kmeleonbrowser.org/ ) ...

Last updated ...

It is December 14, 2022 year ...

So ...

Somewhat confused ...

.
