### ISSUE TITLE
Menu accelerators only work from empty page

### ISSUE THREAD

**Issue by Gavin-Holt** [roytam1/kmeleon#6]
Hi,

Using KM76.2-Goanna-20200321.7z

When I first open to an empty page the Alt+F combination works as expected (OnKeyDown)

Thereafter I have to press Alt, wait for the first menu to highlight, then press F - this is unatural and frustrating.

It is the same for all top level menu accelerators.

Any ideas about how to reinstate normal behaviour?

Kind Regards Gavin Holt

**Comment by roytam1** [comment]
you may ask in http://kmeleonbrowser.org/forum/list.php?19 first.

**Comment by Gavin-Holt** [comment]
Sorry, time to close this issue.
