### ISSUE TITLE
IE Favorites - run arbitrary filetypes

### ISSUE THREAD

**Issue by Gavin-Holt** [roytam1/kmeleon#7]
Hi

I'm new to kmeleon and was pleased to see it can use my existing favorites\links folder, live not just by importing - many thanks.

Some time ago I discovered that placing any file in my existing favorites\links folder would allow me to run it from the IE favorites bar. This includes all files with an associated filetype (e.g. BAT,LUA), lnk files and shortcuts to local or network files.  This serves as a useful launch menu.

Is there an easy way to alter the way kmeleon displays and launches these files to emulate the described functionality?

Kind Regards Gavin Holt

**Comment by roytam1** [comment]
I think it is not suitable to do so in security view
